### ISSUE TITLE
What happened to Figura?

### ISSUE THREAD

**Issue by mcg-anon** [UnlikePaladin/FiguraRewriteRewrite-Forge#1]
Modringht and curseforge pages are down.
Discord is deleted.
Reddit is locked.
Primary repo locked and private

**Comment by Amalyris** [comment]
There has been an issue with the previous lead dev (Francielly) being a predator, and she has removed things to escape consequences. The project will move forward either way, and a new server has been setup https://discord.gg/QNvuSeXN note for @UnlikePaladin, the new team wishes to discuss the possibility of making the forge port official, it'd be appreciated if you could join.

**Comment by mcg-anon** [comment]
thanks for clarification :+1:
